name: Spoon
version: 0.19
abstract: Out of the Cutlery Drawer
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spiffy: 0.21
  IO::All: 0.32
  Template: 2.13
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
