name: Spoon
version: 0.17
abstract: Out of the Cutlery Drawer
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spiffy: 0.19
  IO::All: 0.30
  Template: 2.0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
